services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    command: "server -s3 -s3.config=/etc/seaweedfs/s3.json -dir=/data"
    ports:
      - "8333:8333"
      - "9333:9333"
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json:ro
      - seaweed_data:/data

volumes:
  seaweed_data:
